### ISSUE TITLE
As a user, I want to toggle Weboji on/off

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#1]
This story deals with getting the [Weboji head tracker](https://github.com/jeeliz/jeelizWeboji) working.

## Setup
- [x] Setup vuetify
- [x] Setup preprocessors (Pug, Sass, etc)
- [x] Setup a simple home page

## Tasks
- [x] Setup the Handsfree.js file to be parsed within the vue app
- [x] Setup `const handsfree = new Handsfree(config)`
- [x] Setup `handsfree.start()`

## Cleanup
- [x] Bundle environment into /dist/sandbox
- [x] Bundle handsfree.js into /dist/handsfree
- [x] Publish as handsfree.js v5

**Comment by ozramos** [comment]
Finished! See: https://twitter.com/HeyOzRamos/status/1191943329023512576
