### ISSUE TITLE
As a developer, I need a dev environment

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#1]
## Overview
Let's build off of our [webpack boilerplate](https://github.com/labofoz/ozzys-webpack-boilerplate), add [VuePress](https://vuepress.vuejs.org) for docs, setup a `.github` repository for issue templates, and a CNAME file to get ourselves listed at [handsfreee.js.org](https://handsfree.js.org)

## Tasks
- [ ] Import the webpack boilerplate
- [ ] Install and configure VuePress
- [ ] Create the `/.github/` directory
