### ISSUE TITLE
As a dev, I need to know how to use handsfree up to 1.2.4

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#1]
## Overview
I had a moment and deleted all my repositories. Let's pick up from our last commit and finish up the [documentation site](https://handsfree.js.org)!

## Tasks
- [x] Replace Patreon with $cash link
- [x] Add test/codecov badges
- [x] Debugging
- [ ] Browser Support/Polyfills
- [ ] Testing and mock data
- [ ] The Sandbox

### Settings
- [x] handsfree.settings.target
- [x] handsfree.settings.autostart
- [x] handsfree.settings.facingMode
- [x] handsfree.settings.debug
- [ ] handsfree.settings.canvas
- [ ] handsfree.settings.video
- [ ] handsfree.settings.poseStackSize
- [x] handsfree.settings.posenet
- [x] handsfree.settings.posenet.imageScaleFactor
- [x] handsfree.settings.posenet.multiplier
- [x] handsfree.settings.posenet.maxUsers
- [x] handsfree.settings.posenet.minPoseConfidence
- [x] handsfree.settings.posenet.minPartConfidence
- [x] handsfree.settings.posenet.outputStride
- [x] handsfree.settings.posenet.nmsRadius
- [x] handsfree.settings.posenet.scoreThreshold

### Misc
- [ ] handsfree.poseStack
- [ ] handsfree.cache

### Methods
- [x] handsfree.start()
- [x] Handsfree.stop()
- [x] Handsfree.toggle()
- [ ] Handsfree.toggleAll()
- [x] handsfree.update()
- [x] Handsfree.use()

### Helpers
- [ ] Handsfree.isMobile()
- [ ] Handsfree.isAndroid()
- [ ] Handsfree.isiOS()
- [ ] Handsfree.isWebGLSupported()

### Semi-Privates
- [ ] handsfree._isTracking
- [ ] handsfree._isSupported

### Developer Deep Dive
- [ ] handsfree.trackPoses()
- [ ] handsfree.debugPoses()
- [ ] handsfree.runCalculations()
- [ ] Handsfree.createDefaultVideo()
- [ ] Handsfree.createDefaultCanvas()
- [ ] Handsfree.drawKeypoints()
- [ ] Handsfree.drawSkeleton()
- [ ] Handsfree.toTuple()
- [ ] Handsfree.drawSegment()
- [ ] Handsfree.setDefaults()
- [ ] Handsfree.setAliases()
- [ ] Handsfree.setupFeed()
- [ ] Handsfree.initPoseNet()
- [ ] Handsfree.trackPosesLoop()
- [ ] Handsfree.emitEvents()
- [ ] Handsfree.runPlugins()
- [ ] Handsfree.stopPlugins()

**Comment by labofoz** [comment]
Closing as we're moving to version 2!
