### ISSUE TITLE
As a dev, I want to run plugins by priority

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#10]
## Overview
Let's add a way to sort plugins by priority, which will allow for plugins to depend on one another

## Tasks
- [x] Create the priority API
- [x] Sort plugins by priority
- [x] Allow for updating plugins in real time
- [x] Test
- [x] Document the API

**Comment by labofoz** [comment]
Completed!

![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)
