### ISSUE TITLE
As Ozzy, I want to restructure the APIs

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#12]
## Overview
I'm about to start developing handsfree browsing, and I'm going to get severely confused if I don't clean the code up a bit more. Let's split the codebase into `/api/`, and name our files better.

## Tasks
- [x] Break the module up into subclasses inside `/api/`
- [x] Refactor `mixins` and `helpers`
- [x] Update unit tests

**Comment by labofoz** [comment]
Finished! I didn't update the NPM version since the API is exactly the same
