### ISSUE TITLE
As a dev, I need better accuracy

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#13]
## Overview
I'm feeling ambitious today, so lets improve the accuracy! Lets use the trick we learned on Twitter:
https://twitter.com/LabOfOz/status/996603318087532549

## Notes
I managed to dig up my old algorithm:

```
ratioWidth = window.innerWidth / canvas.width
ratioheight = window.innerHeight / canvas.height
x = -eyeCenter.x * ratioWidth + canvas.width //+ parseInt(this.settings.offset.x) - this.settings.cursor.size / 2
y = eyeCenter.y * ratioHeight //+ parseInt(this.settings.offset.y) - this.settings.cursor.size / 2;
x += Math.sin(pose.rotationY) * (this.settings.speed.x * window.innerWidth) + canvas.offsetLeft,
y += Math.sin(pose.rotationX) * (this.settings.speed.y * window.innerHeight)
```

The trick then is figuring out `pose.rotationY` and `pose.rotationX`

## Tasks
- [x] Calculate position normals (relative to the canvas drawing area)
- [x] Calculate head width
- [x] Calculate head roll
- [ ] Calculate head yaw
- [ ] Calculate head tilt
- [ ] Calculate head.pointedAt

**Comment by labofoz** [comment]
Closing as we're moving to version 2!
