### ISSUE TITLE
As Ozzy, I need a single dashboard to manage everything

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#14]
## Overview
I'm becoming a little overwhelmed with all my various repositories! Let's consolidate everything into a single dashboard that's customizable (for creating turnkey sites like browsehandsfree.com, labofoz.com, and useanything.com)

## Mockup
![793450b9-2f1f-4691-bf8b-b4e0067d9d1a](https://user-images.githubusercontent.com/42591975/45060728-1f15d280-b056-11e8-8195-77e070370e35.jpg)

## Tasks
- [ ] Install and configure [vue-webpack](https://github.com/vuejs-templates/webpack)
- [ ] Setup for working with Pug and Sass
- [ ] Setup [Spectre.css](https://picturepan2.github.io/spectre/getting-started.html) for styles
- [ ] Create the sidebar and two panel areas
- [ ] Make it responsive
- [ ] Build out the sidebar
- [ ] Load Handsfree
- [ ] Create the "Handsfree Debugger" Panel
- ...more planning needed

**Comment by labofoz** [comment]
I separated this out into https://github.com/handsfreejs/dashboard
