### ISSUE TITLE
As a User, I want to control a 1st Person game with my head

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#19]
This story explores the `handsfree.head.position` properties to move a player in 3D space.

## Setup
- [ ] Create the `dungeon-crawler` route
- [ ] Find a demo (maybe a raycaster) that loads very quickly

## Tasks
...

## Cleanup
- [ ] Break out the `handsfree.use` code for each route into it's own file, so that we can link readers to it for studying
- [ ] Write a tutorial on Dev.to
- [ ] Add links to docs
- [ ] Add tweet to home page
