### ISSUE TITLE
As a dev, I need more debugging information

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#2]
## Overview
Seeing the debug canvas itself isn't entirely useful. Let's add the ability to measure performance with [stats.js](https://github.com/mrdoob/stats.js/)

We'll want to update the `debug` and `target` APIs for this. Debug will now be able to accept either a boolean or config object. The config object will be in the following form:

```js
{
  debug: {
    canvas: {
      show: BOOLEAN,
      parent: DOM_ELEMENT
    },
    stats: {
      show: BOOLEAN,
      parent: DOM_ELEMENT
    }
}
```

Passing a boolean essentially enables or disables everything. Doing this will allow us to fine tune the debugging information, which will be useful for me when livestreaming (allowing me to just show the canvas)!

## Tasks
- [x] Include stats.js
- [x] Replace `this.target` with `this.debug.canvas.parent`
- [x] Set stats.js target
- [x] Toggle each independently
- [x] Unit test
- [x] Document

**Comment by labofoz** [comment]
![](http://www.tone.co.uk/wp-content/uploads/2014/05/really-sweating.gif) Next task!
