### ISSUE TITLE
As a user, I need a documentation homepage to learn from

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#2]
## Overview
Let's create a nice VuePress homepage for the docs. Let's try and recreate our logo animation from before as a component:

![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)

Let's model the documentations off of [VuePress](https://vuepress.vuejs.org) and [Vue's](https://vuejs.org/v2/guide/) own documentation sites.

## Tasks
- [x] Setup the homepage
- [x] Add exciting content
- [x] Create a Get Started page
- [x] Add a quickstart snippet

**Comment by labofoz** [comment]
Finished!

![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)
