### ISSUE TITLE
As a user, I want to paint with my face

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#24]
This story involves getting a P5.js sketch working alongside Handsfree.js. The goal is to draw with your face and the purpose is to cover clicking and integration.

## Tasks
- [ ] Create the route
- [ ] Import P5
- [ ] Create the sketch so that it draws a lines when on click mode
- [ ] Two colors: smile left and right
- [ ] Lean in/out to set brush size

## Story cleanup
- [ ] Create Sketch on P5
- [ ] Create Dev.to tutorial
