### ISSUE TITLE
As a user, I want to type via a virtual keyboard

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#29]
Let's use SimpleKeyboard to enable typing handsfree!

## Tasks
- [ ] Create the `keyboard` route
- [ ] Add the virtual keyboard
- [ ] Add different keyboard layouts (letters, digits, emojis)

## Story Cleanup
- [ ] Create post on Dev.to
