### ISSUE TITLE
As a dev, I want to port over code from SeeClarke.js

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#3]
## Overview
Let's bring in as much code as possible from our former project [SeeClarke.js](https://github.com/labofoz/seeclarke.js)

## Tasks
- [x] Import existing codebase
- [x] Setup unit tests
- [x] Replace `SeeClarke.js` with `Handsfree.js`, `SeeClarke` with `Handsfree`, and `seeclarke` with `handsfree`
- [x] Setup Travis and CodeCoverage
- [x] Deploy to npm

**Comment by labofoz** [comment]
Deployed to NPM and is now available at: https://unpkg.com/handsfree

![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)
