### ISSUE TITLE
As a user, I want to use the BodyPix model

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#36]
[BodyPix](https://github.com/tensorflow/tfjs-models/tree/master/body-pix) is a "person segmentation" model. I'm not 100% sure how we'll use this for handsfree interactions yet, but I think that it'll be an effective way to create a "green screen" from which I can start doing YouTube tutorials around...kind of like [Coding Train](https://www.youtube.com/channel/UCvjgXvBlbQiydffZU7m1_aw).

## Tasks
- [x] Include the model as a package
- [x] Handle initialization code with Handsfree.js
- [x] pass in `models.bodypix.enabled = true` to enable the model
- [x] Handle config options
- [x] Handle game loop
- [x] Include source maps for TensorFlow and Bodypix

## Inspiration
- [x] https://twitter.com/zachlieberman/status/1187423974302588929
