### ISSUE TITLE
As a user, I want to throttle clicks

### ISSUE THREAD

**Issue by ozramos** [handsfreejs/handsfree#43]
In some situations, it might be necessary to only allow clicking every so often. Use cases include:

- **Avoiding misclicks** - A small throttle can help avoid misclicks caused by inaccuracies when a morph hovers right around the threshold (smiling just enough to click can cause lots of clicks)
- **Game cooldowns** - Add a feature to games that create a cooldown effect, where you can only click every x seconds

## Tasks
- [x] Create an example with a grid of buttons for testing
- [x] Add a throttle config to the clicking
- [x] Throttle clicking
- [x] Add a `.updateClickThrottle(milliseconds)` to the plugin so that we can update them later
- [x] Set a good default (not zero)
- [x] Update head.click plugin with the new throttle logic
- [x] Document this feature
