### ISSUE TITLE
As Ozzy, I want a flashier hero unit for the documentation site

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#5]
## Overview
The main hero unit is super boring. Let's create an [A-Frame](https://aframe.io) synthwave scene with our "Surprise" gif overlaid ontop of it:

### Surprise Gif
![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)

### Synthwave Scene
https://aframe.io/examples/showcase/hello-metaverse/

![image](https://user-images.githubusercontent.com/42591975/44474317-3af58f00-a5e7-11e8-9ba7-de29eca02897.png)

### Tasks
- [ ] Recreate the GIF with CSS/SVG
- [ ] Create the synthwave scene
- [ ] Overlay the logo on top, animated so that it looks like it's moving around
- [ ] Show a GIF of me using it, with a greenscreen
- [ ] Add a start button that allows the user to look around
- [ ] Update the theme colors to match the synthwave theme

**Comment by labofoz** [comment]
Closing as we're moving to version 2!
