### ISSUE TITLE
As a dev, I want to hotswap PoseNet with BRFv4

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#6]
## Overview
[PoseNet](https://github.com/tensorflow/tfjs-models/tree/master/posenet) is fast and lightweight. It's great for general pose estimation, but we could improve head tracking dramatically by adding in a dedicated face tracker. Let's add the ability to swap out the model with [BRFv4](https://github.com/Tastenkunst/brfv4_javascript_examples).

## Tasks
- [ ] Import BRFv4
- [ ] Include instructions for requiring the BRFv4 dependency
- [ ] Load BRFv4
- [ ] Add settings for BRFv4
- [ ] Position the cursor
- [ ] Test
- [ ] Document

**Comment by labofoz** [comment]
Closing as we're moving to version 2!
