### ISSUE TITLE
As a dev, I want #handsfree-debug-wrapper to be the default debug target

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#6]
## Overview
To help simplify things a bit, let's make `#handsfree-debug-wrapper` the default target. If it doesn't exist we'll create it and stick it at the top of the document absolutely.

## Tasks
- [x] Use `#handsfree-debug-wrapper` as default target
- [x] If it doesn't exist create it
- [x] Unit test
- [x] Resize canvas height with video height on window.resize
- [x] Document

**Comment by labofoz** [comment]
Done

![](https://media.giphy.com/media/1YfCgZlRFN9JqfrtRC/giphy.gif)
