### ISSUE TITLE
As a user, I need a settings control panel

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#7]
## Overview
![](https://github.com/freeman-lab/control-panel/raw/master/images/themes.png)

The process for testing different settings is excruciatingly slow, as we currently need to:
- Manually edit the setting
- Save the script
- Rebuild
- Reload page
- Start handsfree
- Test setting

With a control panel, we (and our users) can just update the settings live! Let's use [control-panel](https://github.com/freeman-lab/control-panel) for this. Let's also build this as a plugin, so that others can opt-out of the panel in production environments etc

## Tasks
- [x] Create a `/plugins/ControlPanel.js` plugin
- [x] On init, create a panel and field for each setting
- [x] On change, simply update the setting
- [x] Unit test
- [x] Update documentation

**Comment by labofoz** [comment]
`control-panel` is too limiting. Let's try [datgui](https://github.com/dataarts/dat.gui) instead

**Comment by labofoz** [comment]
Finished and documented!

![](https://i.imgur.com/b1Fn8rVl.png)
