### ISSUE TITLE
As a dev, I want default pointers

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#7]
## Overview
Let's simplify things for devs a bit and add default pointers. Let's make this the default behavior!

## Tasks
- [ ] Add a `onPose` method to simplify the window event
- [ ] Remember the number of poses from the last frame and add/remove poses accordingly (perhaps throttle this, to maintain performance in low light environments (where the pose may "flicker").
- [ ] Position a pointer for the user
- [ ] Make this the default
- [ ] Document
- [ ] Demo
- [ ] Test
