### ISSUE TITLE
Livestream: Create a bookmarklet that lets you scroll pages and click on things

### ISSUE THREAD

**Issue by labofoz** [handsfreejs/handsfree#8]
## Overview
In this livestream, we'll be going over how to add page scrolling and clicking. We'll be wrapping this up into a bookmarklet, which will allow us to test on any site on the web. Eventually, this bookmarklet be turned into a browser extension!

## Tasks
- [ ] Scroll pages up and down
- [ ] Scroll pages left and right
- [ ] Add a control panel to adjust settings
- [ ] Wrap as a bookmarklet

## Sites to test on
- [ ] Wikipedia
- [ ] YouTube

## Stretch Goals
* Reuse technique to peek around in YouTube videos

**Comment by labofoz** [comment]
Moved to: https://github.com/handsfreejs/bookmarklet/issues/1
